const brands=[['Pro Plan','پروپلن'],['Royal Canin','رویال کنین'],['Josera','جوسرا'],['Wanpy','ونپی'],['Happy Cat','هپی کت'],['Monello','مونلو'],['Reflex Plus','رفلکس پلاس'],['Brit Care','بریت کر'],['Farmina N&D','فارمینا'],['Taste of the Wild','تیست آو د وایلد'],['Hill’s','هیلز'],['Schesir','شسیر']];
const products=[
{id:1,title:'Persian Adult',fa:'رویال کنین پرشین ادالت',brand:'Royal Canin',type:'cat',age:'adult',tag:'گربه پرشین',color:'linear-gradient(#d7af57,#9b681c)',desc:'مناسب گربه پرشین بالغ بالای ۱۲ ماه؛ کمک به سلامت پوست، مو و دفع گلوله مویی.',protein:'۳۰٪',fat:'۲۲٪',for:'گربه پرشین بالغ',avoid:'بچه‌گربه و دوره بارداری'},
{id:2,title:'Sterilised Adult',fa:'پروپلن استریلایزد',brand:'Pro Plan',type:'cat',age:'adult',tag:'عقیم‌شده',color:'linear-gradient(#1e2329,#535b65)',desc:'کنترل وزن و حمایت از سلامت دستگاه ادراری در گربه‌های عقیم‌شده بالغ.',protein:'۴۱٪',fat:'۱۲٪',for:'گربه عقیم‌شده',avoid:'نیازهای درمانی خاص'},
{id:3,title:'Kitten',fa:'جوسرا کیتن',brand:'Josera',type:'cat',age:'kitten',tag:'رشد',color:'linear-gradient(#f4cc32,#b98900)',desc:'انرژی و پروتئین متناسب با رشد بچه‌گربه، همراه با ترکیبات کمک‌کننده به هضم.',protein:'۳۵٪',fat:'۱۸٪',for:'۲ تا ۱۲ ماه',avoid:'گربه بالغ کم‌تحرک'},
{id:4,title:'Mini Adult',fa:'رویال کنین مینی ادالت',brand:'Royal Canin',type:'dog',age:'adult',tag:'نژاد کوچک',color:'linear-gradient(#e9d2a6,#b7202a)',desc:'مناسب سگ‌های بالغ نژاد کوچک با وزن ۱ تا ۱۰ کیلوگرم.',protein:'۲۷٪',fat:'۱۶٪',for:'سگ کوچک ۱۰ ماه تا ۸ سال',avoid:'سگ نژاد بزرگ'},
{id:5,title:'Puppy Medium',fa:'پروپلن پاپی مدیوم',brand:'Pro Plan',type:'dog',age:'kitten',tag:'توله سگ',color:'linear-gradient(#61222c,#151515)',desc:'فرمول رشد برای توله‌سگ‌های نژاد متوسط؛ حمایت از ایمنی و رشد استخوان‌ها.',protein:'۳۰٪',fat:'۱۹٪',for:'توله نژاد متوسط',avoid:'سگ بالغ'},
{id:6,title:'Renal Special',fa:'رویال کنین رنال اسپشیال',brand:'Royal Canin',type:'medical',age:'adult',tag:'درمانی',color:'linear-gradient(#d9c4a8,#7d5633)',desc:'رژیم دامپزشکی برای حمایت تغذیه‌ای از کلیه؛ مصرف فقط با نظر دامپزشک.',protein:'۲۶٪',fat:'۱۷٪',for:'بیماری مزمن کلیه',avoid:'بدون تجویز دامپزشک'},
{id:7,title:'Indoor 27',fa:'رویال کنین ایندور ۲۷',brand:'Royal Canin',type:'cat',age:'adult',tag:'داخل خانه',color:'linear-gradient(#d5b378,#a86822)',desc:'مناسب گربه‌های بالغ کم‌تحرک داخل خانه؛ کمک به کاهش بوی مدفوع و گلوله مویی.',protein:'۲۷٪',fat:'۱۳٪',for:'گربه داخل خانه',avoid:'گربه بسیار فعال'},
{id:8,title:'Adult Salmon',fa:'هپی کت سالمون',brand:'Happy Cat',type:'cat',age:'adult',tag:'پوست و مو',color:'linear-gradient(#4a72a8,#efb046)',desc:'حاوی ماهی سالمون و اسیدهای چرب برای کمک به پوست و موی سالم.',protein:'۳۳٪',fat:'۱۵٪',for:'گربه بالغ',avoid:'حساسیت به ماهی'}];
const brandGrid=document.querySelector('#brandGrid'),productGrid=document.querySelector('#productGrid'),brandFilter=document.querySelector('#brandFilter');
function renderBrands(limit=6){brandGrid.innerHTML=brands.slice(0,limit).map(b=>`<button class="brand-card" data-brand="${b[0]}" title="${b[1]}">${b[0]}</button>`).join('')}
function renderProducts(list=products){productGrid.innerHTML=list.map(p=>`<article class="product-card" data-id="${p.id}" tabindex="0"><span class="tag">${p.tag}</span><div class="product-thumb"><div class="mini-bag" style="background:${p.color}">${p.brand}<br><small>${p.title}</small></div></div><div class="product-info"><small>${p.brand}</small><h3>${p.fa}</h3><p>${p.desc}</p></div></article>`).join('')}
function openProduct(id){const p=products.find(x=>x.id===Number(id));if(!p)return;document.querySelector('#dialogContent').innerHTML=`<div class="dialog-product"><div class="product-thumb"><div class="mini-bag" style="background:${p.color}">${p.brand}<br><small>${p.title}</small></div></div><div><small>${p.brand}</small><h2>${p.fa}</h2><p>${p.desc}</p><div class="specs"><div><b>سن و گروه مناسب</b><br>${p.for}</div><div><b>پروتئین تقریبی</b><br>${p.protein}</div><div><b>چربی تقریبی</b><br>${p.fat}</div><div><b>نامناسب برای</b><br>${p.avoid}</div></div><p><b>نکته:</b> اطلاعات نهایی هر محصول باید با بسته‌بندی رسمی همان بازار و نظر دامپزشک تطبیق داده شود.</p></div></div>`;document.querySelector('#productDialog').showModal()}
renderBrands();renderProducts();brands.forEach(b=>brandFilter.insertAdjacentHTML('beforeend',`<option value="${b[0]}">${b[1]}</option>`));
brandGrid.addEventListener('click',e=>{const b=e.target.closest('[data-brand]');if(b){renderProducts(products.filter(p=>p.brand===b.dataset.brand));document.querySelector('#products').scrollIntoView()}});
productGrid.addEventListener('click',e=>{const c=e.target.closest('[data-id]');if(c)openProduct(c.dataset.id)});
document.querySelectorAll('.chips button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.chips button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');renderProducts(btn.dataset.filter==='all'?products:products.filter(p=>p.type===btn.dataset.filter))}));
document.querySelector('#allBrands').addEventListener('click',e=>{const x=e.target.dataset.expanded==='1';renderBrands(x?6:brands.length);e.target.dataset.expanded=x?'0':'1';e.target.textContent=x?'مشاهده همه برندها ←':'نمایش کمتر ←'});
document.querySelector('#finderButton').addEventListener('click',()=>{const t=document.querySelector('#petType').value,b=brandFilter.value,a=document.querySelector('#ageFilter').value;renderProducts(products.filter(p=>(t==='all'||p.type===t)&&(b==='all'||p.brand===b)&&(a==='all'||p.age===a)));document.querySelector('#products').scrollIntoView()});
document.querySelectorAll('dialog .dialog-close').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));document.querySelector('[data-search-open]').addEventListener('click',()=>document.querySelector('#searchDialog').showModal());document.querySelector('#globalSearch').addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase(),hits=q?products.filter(p=>[p.fa,p.brand,p.title,p.desc,p.tag].join(' ').toLowerCase().includes(q)):[];document.querySelector('#searchResults').innerHTML=hits.map(p=>`<div class="search-hit" data-search-id="${p.id}"><b>${p.fa}</b><br><small>${p.brand} — ${p.tag}</small></div>`).join('')||'<p>عبارت موردنظر را وارد کنید.</p>'});document.querySelector('#searchResults').addEventListener('click',e=>{const h=e.target.closest('[data-search-id]');if(h){document.querySelector('#searchDialog').close();openProduct(h.dataset.searchId)}});document.querySelector('#vetSearch').addEventListener('click',()=>alert('در نسخه متصل به پنل مدیریت، نتایج شهر انتخاب‌شده از پایگاه داده نمایش داده می‌شوند.'));document.querySelector('#newsletter').addEventListener('submit',e=>{e.preventDefault();alert('ایمیل شما ثبت شد.');e.target.reset()});if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});